language: node_js
node_js:
      - 8

cache:
      directories:
            - node_modules

notifications:
      email:
            recipients:
                  - email@address.com
            on_success: change
            on_failure: change

install:
      - 'yarn add coveralls'

script:
      - yarn test --coverage --coverageReporters=text-lcov --detectOpenHandles --forceExit | coveralls
      - yarn build
