language: node_js
node_js:
      - 8

cache:
      directories:
            - node_modules

notifications:
      email:
            recipients:
                  - email@address.com
            on_success: change
            on_failure: change

install:
      - 'yarn add coveralls'

script:
      - yarn test --coverage --coverageReporters=text-lcov --detectOpenHandles --forceExit | coveralls
      - yarn build

deploy:
      provider: s3
      access_key_id: "AKIAJCJNSV4XCNS3UQAQ"
      bucket: "my-route-planner"
      local_dir: build
      on:
            branch: master
      secret_access_key: "omAO3oaxrNUydPpSxfHGtg7y4URuiOez5bTXZy1P"